export const emails = [
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "8:38 AM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Minerva Barnett",
    label: "Work",
    title: "Get Best Advertiser In Your Side Pocket",
    date: "8:13 AM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Peter Lewis",
    label: "Friends",
    title: "Vacation Home Rental Success",
    date: "7:52 PM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Anthony Briggs",
    label: "",
    title: "Free Classifieds Using Them To Promote Your Stuff Online",
    date: "7:52 PM",
    isStared: true,
    isSelected: false,
  },
  {
    sender: "Clifford Morgan",
    label: "Social",
    title: "Enhance Your Brand Potential With Giant Advertising Blimps",
    date: "4:13 PM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Cecilia Webster",
    label: "Friends",
    title: "Always Look On The Bright Side Of Life",
    date: "3:52 PM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Harvey Manning",
    label: "",
    title: "Curling Irons Are As Individual As The Women Who Use Them",
    date: "2:30 PM",
    isStared: true,
    isSelected: false,
  },
  {
    sender: "Willie Blake",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "8:38 AM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Minerva Barnett",
    label: "Work",
    title: "Get Best Advertiser In Your Side Pocket",
    date: "8:13 AM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Fanny Weaver",
    label: "",
    title: "Free Classifieds Using Them To Promote Your Stuff Online",
    date: "7:52 PM",
    isStared: true,
    isSelected: false,
  },
  {
    sender: "Olga Hogan",
    label: "Social",
    title: "Enhance Your Brand Potential With Giant Advertising Blimps.",
    date: "4:13 PM",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Lora Houston",
    label: "Friends",
    title: "Vacation Home Rental Success",
    date: "7:52 PM",
    isStared: false,
    isSelected: false,
  },
];
