export const emails = [
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Minerva Barnett",
    label: "Work",
    title: "Get Best Advertiser In Your Side Pocket",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Peter Lewis",
    label: "Friends",
    title: "Vacation Home Rental Success",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Anthony Briggs",
    label: "",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: true,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
  {
    sender: "Jullu Jalal",
    label: "Primary",
    title: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2024-03-27T13:56:29.888Z",
    isStared: false,
    isSelected: false,
  },
];
