export const pricing = [
  {
    quality: "Basic",
    pay: "Monthly Charge",
    price: "$14.99",
    features: [
      { setup: "Free Setup", available: true },
      { limit: "Bandwidth Limit 10 GB", available: true },
      { userConnection: "20 User Connection", available: true },
      { analytics: "Analytics Report", available: false },
      { apiAccess: "Public API Access", available: false },
      { plugins: "Plugins Integration", available: false },
      { contentManage: "Custom Content Manage", available: false },
    ],
    button: "Get Started",
    freeTrial: "Start Your 30 Day Free Trial",
  },
  {
    quality: "Standard",
    pay: "Monthly Charge",
    price: "$49.99",
    features: [
      { setup: "Free Setup", available: true },
      { limit: "Bandwidth Limit 10 GB", available: true },
      { userConnection: "20 User Connection", available: true },
      { analytics: "Analytics Report", available: true },
      { apiAccess: "Public API Access", available: true },
      { plugins: "Plugins Integration", available: false },
      { contentManage: "Custom Content Manage", available: false },
    ],
    button: "Get Started",
    freeTrial: "Start Your 30 Day Free Trial",
  },
  {
    quality: "Premium",
    pay: "Monthly Charge",
    price: "$89.99",
    features: [
      { setup: "Free Setup", available: true },
      { limit: "Bandwidth Limit 10 GB", available: true },
      { userConnection: "20 User Connection", available: true },
      { analytics: "Analytics Report", available: true },
      { apiAccess: "Public API Access", available: true },
      { plugins: "Plugins Integration", available: true },
      { contentManage: "Custom Content Manage", available: true },
    ],
    button: "Get Started",
    freeTrial: "Start Your 30 Day Free Trial",
  },
];
