export const pricing = [
  {
    quality: "Basic",
    pay: "Monthly Charge",
    price: "$14.99",
    setup: true,
    limit: true,
    userConnection: true,
    analytics: false,
    apiAccess: false,
    plugins: false,
    contentManage: false,
    button: "Get Started",
    freeTrial: "Start Your 30 Day Free Trial",
  },
  {
    quality: "Standard",
    pay: "Monthly Charge",
    price: "$49.99",
    setup: true,
    limit: true,
    userConnection: true,
    analytics: true,
    apiAccess: true,
    plugins: false,
    contentManage: false,
    button: "Get Started",
    freeTrial: "Start Your 30 Day Free Trial",
  },
  {
    quality: "Premium",
    pay: "Monthly Charge",
    price: "$89.99",
    setup: true,
    limit: true,
    userConnection: true,
    analytics: true,
    apiAccess: true,
    plugins: true,
    contentManage: true,
    button: "Get Started",
    freeTrial: "Start Your 30 Day Free Trial",
  },
];
